"""Run the frozen experimental-structure, B3/B4, and sensitivity analysis."""

from __future__ import annotations

import argparse
import hashlib
import json
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml

from assay_context.artifacts import external_artifact_path
from assay_context.evaluate import evaluate_binary
from assay_context.sensitivity import (
    assert_common_variant_ids,
    assert_complete_b4_b2_contrasts,
    assign_proximity,
    compare_structure_models,
    paired_prediction_bootstrap,
    structure_complete_case,
    validate_sensitivity_evidence,
    verify_external_sha256,
)
from assay_context.structure import map_structure

PRIMARY_STRUCTURES = {
    "CYP2C9": {"pdb_id": "1R9O", "chain": "A", "uniprot": "P11712", "structure_sha256": "16860aca35da55e576db41e3ff6a69227b41f771ba5ff4691d1d61eeef10e136", "uniprot_sha256": "04225b238d8651585744c51ef485bf68776794b5c950c8496e6597f12766b9cb", "functional_positions": (435,), "site_source": "UniProtKB/Swiss-Prot P11712 binding-site feature (entry version frozen at retrieval)"},
    "PTEN": {"pdb_id": "1D5R", "chain": "A", "uniprot": "P60484", "structure_sha256": "efd284b66f0f66d6c78c42aebe743c2095165878c097eff1eddee1f57653914c", "uniprot_sha256": "e0f06e38d1d104d40bba113d5d1d6d904c5f51d68ff4fdca2701f263505d4c75", "functional_positions": (124,), "site_source": "UniProtKB/Swiss-Prot P60484 active-site feature (entry version frozen at retrieval)"},
}
PASS_PROTEINS = tuple(PRIMARY_STRUCTURES)
CASE_RULE = (
    "deterministically selected post-analysis using a recorded rule; Task 4 B2 OOF "
    "false-negative lowest probability; true-positive highest probability; uncertain "
    "abundance-preserved/function-uncertain closest to within-protein median ESM1v score"
)
SITE_ENTRY_VERSIONS = {"CYP2C9": 252, "PTEN": 226}


def structure_evaluation_freeze() -> dict[str, object]:
    """Return the structure-stage contract regenerated by the final pipeline stage."""
    structures = {}
    for protein, spec in PRIMARY_STRUCTURES.items():
        pdb_id = str(spec["pdb_id"])
        accession = str(spec["uniprot"])
        structures[protein] = {
            "pdb_id": pdb_id,
            "chain": spec["chain"],
            "official_url": f"https://files.rcsb.org/download/{pdb_id}.pdb",
            "metadata_url": f"https://data.rcsb.org/rest/v1/core/entry/{pdb_id}",
            "uniprot_accession": accession,
            "site_annotation_url": f"https://rest.uniprot.org/uniprotkb/{accession}.txt",
            "site_annotation_entry_version": SITE_ENTRY_VERSIONS[protein],
            "functional_positions": list(spec["functional_positions"]),
        }
    return {
        "primary_proteins": list(PASS_PROTEINS),
        "selection_rule": (
            "experimental structure selected before model-error inspection; "
            "fallback is official AlphaFold DB only if mapping gates fail"
        ),
        "mapping_gates": {
            "chain_identity_minimum": 0.95,
            "reference_coverage_minimum": 0.65,
        },
        "structures": structures,
        "feature_rules": {
            "accessibility": (
                "relative SASA by deterministic Shrake-Rupley sphere and Tien-2013 "
                "maximum ASA scale"
            ),
            "secondary_structure": (
                "PDB HELIX/SHEET records; unassigned mapped residues are coil"
            ),
            "contacts": (
                "any heavy-atom distance <= 8 Angstrom; exclude same and "
                "sequence-adjacent residues"
            ),
            "site_distance": (
                "minimum heavy-atom distance to independently annotated mapped "
                "functional residues"
            ),
            "proximity_descriptive_angstrom": 5,
            "proximity_sensitivity_angstrom": [4, 8],
            "confidence_experimental": "mean atom B-factor; pLDDT remains NaN",
            "confidence_alphafold": "atom pLDDT; never interpreted as stability",
        },
        "case_rule": CASE_RULE,
    }


def update_analysis_freeze(config_path: Path) -> None:
    """Restore the structure contract while preserving completed earlier stages."""
    freeze = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    freeze["structure_evaluation"] = structure_evaluation_freeze()
    config_path.write_text(
        yaml.safe_dump(freeze, sort_keys=False, allow_unicode=False),
        encoding="utf-8",
    )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _download_structure(pdb_id: str, directory: Path) -> tuple[Path, dict[str, object]]:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{pdb_id.lower()}.pdb"
    url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    if not path.exists():
        with urllib.request.urlopen(url, timeout=60) as response:
            path.write_bytes(response.read())
    metadata_url = f"https://data.rcsb.org/rest/v1/core/entry/{pdb_id}"
    with urllib.request.urlopen(metadata_url, timeout=60) as response:
        metadata = json.loads(response.read().decode("utf-8"))
    exptl = (metadata.get("exptl") or [{}])[0]
    refine = (metadata.get("refine") or [{}])[0]
    resolution = refine.get("ls_dres_high")
    if resolution is None:
        combined = (metadata.get("rcsb_entry_info") or {}).get("resolution_combined") or []
        resolution = combined[0] if combined else None
    return path, {
        "structure_id": pdb_id,
        "chain": "A",
        "official_url": url,
        "metadata_url": metadata_url,
        "retrieved_at": datetime.fromtimestamp(path.stat().st_mtime, UTC).isoformat(),
        "sha256": _sha256(path),
        "experimental_method": exptl.get("method"),
        "resolution_angstrom": resolution,
    }


def _download_uniprot_annotation(accession: str, directory: Path) -> dict[str, object]:
    """Retrieve independent UniProt feature provenance for frozen site positions."""
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"uniprot_{accession}.txt"
    url = f"https://rest.uniprot.org/uniprotkb/{accession}.txt"
    if not path.exists():
        with urllib.request.urlopen(url, timeout=60) as response:
            path.write_bytes(response.read())
    text = path.read_text(encoding="utf-8", errors="replace")
    versions = [line.split("entry version", 1)[1].strip().rstrip(".") for line in text.splitlines() if "entry version" in line]
    features = [line.strip() for line in text.splitlines() if line.startswith(("FT   ACT_SITE", "FT   BINDING"))]
    return {"accession": accession, "official_url": url, "retrieved_at": datetime.fromtimestamp(path.stat().st_mtime, UTC).isoformat(), "sha256": _sha256(path), "entry_version": versions[0] if versions else None, "site_features": features}


def _load_sequences() -> dict[str, str]:
    inventory = pd.read_csv("results/metadata/assay_inventory.csv")
    rows = inventory.loc[inventory["role"].eq("abundance")]
    return dict(rows.set_index("protein_id")["sequence"])


def _structure_maps(work_dir: Path) -> tuple[pd.DataFrame, list[dict[str, object]]]:
    sequences = _load_sequences()
    rows: list[pd.DataFrame] = []
    provenance: list[dict[str, object]] = []
    for protein, spec in PRIMARY_STRUCTURES.items():
        protein_id = {"CYP2C9": "CP2C9_HUMAN", "PTEN": "PTEN_HUMAN"}[protein]
        path, meta = _download_structure(spec["pdb_id"], work_dir)
        annotation = _download_uniprot_annotation(spec["uniprot"], work_dir)
        if meta["sha256"] != spec["structure_sha256"]:
            raise ValueError(f"frozen structure SHA256 mismatch for {spec['pdb_id']}; refusing to overwrite source")
        if annotation["sha256"] != spec["uniprot_sha256"]:
            raise ValueError(f"frozen UniProt SHA256 mismatch for {spec['uniprot']}; refusing to overwrite source")
        mapped = map_structure(sequences[protein_id], str(path), spec["chain"], functional_positions=spec["functional_positions"], functional_site_source=spec["site_source"])
        mapped.insert(0, "protein", protein)
        mapped.insert(1, "structure_id", spec["pdb_id"])
        rows.append(mapped)
        meta.update({"protein": protein, "reference_sequence_hash": hashlib.sha256(sequences[protein_id].encode()).hexdigest(), "mapping_identity": mapped.attrs["mapping_identity"], "mapping_coverage": mapped.attrs["mapping_coverage"], "sequence_mapping_rule": "global Needleman-Wunsch; identity >=0.95 and reference coverage >=0.65", "functional_site_source": spec["site_source"], "functional_site_positions": spec["functional_positions"], "independent_annotation": annotation, "confidence_rule": mapped.attrs["confidence_definition"]})
        provenance.append(meta)
    return pd.concat(rows, ignore_index=True), provenance


def _joined_primary() -> pd.DataFrame:
    cohort = pd.read_csv("D:/protein_assay_work/processed/paired_phenotype_cohort.csv")
    atlas = pd.read_csv(external_artifact_path("assay_atlas.csv"))
    keys = ["protein", "sequence_hash", "wt", "position", "mutant", "variant"]
    scores = atlas[keys + ["ESM1v_single_impairment", "ESM2_650M_impairment"]]
    frame = cohort.merge(scores, on=keys, how="left", validate="one_to_one")
    frame = frame.loc[frame["primary_eligible"].astype(bool) & frame["protein"].isin(PASS_PROTEINS)].copy()
    oof = pd.read_csv(external_artifact_path("task4_oof_predictions.csv"))
    oof = oof.loc[oof["feature_set"].eq("B2"), ["protein", "variant", "position", "fold"]]
    if oof.duplicated(["protein", "variant", "position"]).any():
        raise ValueError("Task 4 B2 OOF fold assignment is not unique")
    frame = frame.merge(oof, on=["protein", "variant", "position"], how="inner", validate="one_to_one")
    return frame


def _metrics(predictions: pd.DataFrame, setting: str) -> pd.DataFrame:
    rows = []
    for (protein, feature), group in predictions.groupby(["protein", "feature_set"], sort=True):
        result = evaluate_binary(group["y_true"].to_numpy(), group["prediction"].to_numpy())
        rows.append({"setting": setting, "protein": protein, "feature_set": feature, **result})
    return pd.DataFrame(rows)


def _alternate_score_metrics(primary: pd.DataFrame, source: Path) -> pd.DataFrame:
    """Evaluate the frozen function-assay score source without coalescing it."""
    raw = pd.read_csv(source)
    required = {"protein", "protein_id", "sequence_hash", "variant", "wt", "position", "mutant", "model", "score"}
    missing = sorted(required - set(raw.columns))
    if missing:
        raise ValueError(f"function sensitivity source is missing: {', '.join(missing)}")
    raw = raw.loc[raw["model"].isin(("ESM1v_single", "ESM2_650M"))].copy()
    raw["score"] = pd.to_numeric(raw["score"], errors="coerce")
    key = ["protein", "sequence_hash", "wt", "position", "mutant", "variant"]
    if raw.duplicated(key + ["model"]).any():
        raise ValueError("function sensitivity source contains duplicate canonical model keys")
    pivot = raw.pivot(index=key, columns="model", values="score").reset_index()
    rows = []
    for model in ("ESM1v_single", "ESM2_650M"):
        column = model
        joined = primary.merge(pivot[key + [column]], on=key, how="left", validate="one_to_one")
        joined = joined.dropna(subset=[column])
        for protein, group in joined.groupby("protein", sort=True):
            result = evaluate_binary(group["primary_endpoint"].eq("function-impaired").astype(int).to_numpy(), -group[column].to_numpy())
            rows.append({"score_source": "function-assay ProteinGym sensitivity", "protein": protein, "model": model, **result})
    return pd.DataFrame(rows)


def _bootstrap_summaries(predictions: pd.DataFrame, setting: str, output: Path, seed: int = 2026, draws: int = 2000) -> pd.DataFrame:
    """Write paired draw rows externally and retain compact AP/contrast CIs."""
    draw_frame = paired_prediction_bootstrap(predictions, setting=setting, seed=seed, n_boot=draws)
    output.parent.mkdir(parents=True, exist_ok=True)
    mode = "w" if not output.exists() else "a"
    draw_frame.to_csv(output, index=False, mode=mode, header=mode == "w")
    rows: list[dict[str, object]] = []
    for (protein, model), group in draw_frame.groupby(["protein", "model"], sort=True):
        observed = predictions.loc[(predictions["protein"].eq(protein)) & predictions["feature_set"].eq(model)]
        point = evaluate_binary(observed["y_true"].to_numpy(), observed["prediction"].to_numpy())
        valid = group.loc[group["valid"].astype(bool), "ap"]
        rows.append({"setting": setting, "protein": protein, "model": model, "n_variants": len(observed), "n_positions": int(observed["position"].nunique()), "prevalence": point["prevalence"], "ap": point["ap"], "ap_ci_low": valid.quantile(0.025) if len(valid) else np.nan, "ap_ci_high": valid.quantile(0.975) if len(valid) else np.nan, "invalid_fraction": float(1 - len(valid) / draws), "seed": seed, "n_boot": draws, "ci_interpretation": "measured residue positions only"})
    wide = draw_frame.pivot_table(index=["protein", "draw"], columns="model", values="ap").reset_index()
    for left, right in (("B2", "B3"), ("B2", "B4"), ("B3", "B4")):
        contrast = wide[right] - wide[left]
        valid = contrast.dropna()
        for protein, values in contrast.groupby(wide["protein"]):
            vals = values.dropna()
            rows.append({"setting": setting, "protein": protein, "model": f"{right}-{left}", "n_variants": int(predictions.loc[predictions["protein"].eq(protein), "variant"].nunique()), "n_positions": int(predictions.loc[predictions["protein"].eq(protein), "position"].nunique()), "prevalence": np.nan, "ap": vals.mean() if len(vals) else np.nan, "ap_ci_low": vals.quantile(0.025) if len(vals) else np.nan, "ap_ci_high": vals.quantile(0.975) if len(vals) else np.nan, "invalid_fraction": float(1 - len(vals) / draws), "seed": seed, "n_boot": draws, "ci_interpretation": "paired measured-position bootstrap contrast"})
    return pd.DataFrame(rows)


def _sensitivity_results(primary: pd.DataFrame, within: pd.DataFrame, complete: pd.DataFrame | None, lopo: pd.DataFrame, function_metrics: pd.DataFrame | None, draw_summary: pd.DataFrame, draw_path: Path, output: Path) -> pd.DataFrame:
    """Build machine-checkable quantitative sensitivity evidence rows."""
    rows: list[dict[str, object]] = []
    def add(control: str, protein: str, setting: str, model: str, group: pd.DataFrame, metric: float | None, effect: float | None, status: str, reason: str, evidence: str, *, stratum: str = "primary", common_ids: int | None = None, available_ids: int | None = None, ci_low: float | None = None, ci_high: float | None = None, source_sha256: str | None = None, hash_validated: bool | None = None) -> None:
        if "primary_endpoint" in group:
            positives = int(group["primary_endpoint"].eq("function-impaired").sum())
            negatives = int(group["primary_endpoint"].eq("function-preserved").sum())
        elif "y_true" in group:
            positives = int(pd.to_numeric(group["y_true"], errors="coerce").eq(1).sum())
            negatives = int(pd.to_numeric(group["y_true"], errors="coerce").eq(0).sum())
        else:
            positives = negatives = np.nan
        rows.append({"control": control, "protein": protein, "setting": setting, "model": model, "stratum": stratum, "n_variants": len(group), "n_positions": int(group["position"].nunique()) if "position" in group else 0, "positives": positives, "negatives": negatives, "common_ids": common_ids, "available_ids": available_ids, "metric": metric, "effect": effect, "ci_low": ci_low, "ci_high": ci_high, "source_sha256": source_sha256, "hash_validated": hash_validated, "status": status, "reason": reason, "evidence": evidence})
    direct = {}
    for protein, group in primary.groupby("protein", sort=True):
        labels = group["primary_endpoint"].eq("function-impaired").astype(int).to_numpy()
        for model, column in (("ESM1v_single", "ESM1v_single_impairment"), ("ESM2_650M", "ESM2_650M_impairment")):
            direct[(protein, model)] = evaluate_binary(labels, group[column].to_numpy())
    if function_metrics is not None:
        for row in function_metrics.itertuples(index=False):
            point = direct[(row.protein, row.model)]
            source = function_metrics.loc[function_metrics["protein"].eq(row.protein) & function_metrics["model"].eq(row.model)]
            source_n = int(source["n_variants"].iloc[0]) if not source.empty else 0
            group = primary.loc[primary["protein"].eq(row.protein)]
            add("function_score_source", row.protein, "direct", row.model, group, row.ap, row.ap - point["ap"], "PASS" if source_n == len(group) else "FAILED", f"primary versus frozen function-file score AP delta={row.ap - point['ap']:+.6f}; common IDs={source_n}, primary IDs={len(group)}; source hash validated before use", "results/metadata/task5_function_score_sensitivity.csv", common_ids=min(source_n, len(group)), available_ids=source_n, source_sha256="3be0cc1eec7ef6b3da5da9289c22e1170758eaeaa773692741b554b83888be4b", hash_validated=True)
    for protein, group in primary.groupby("protein", sort=True):
        for kind, series in (("function_uncertainty_kind", group.get("function_uncertainty_kind", pd.Series(index=group.index, dtype="string"))), ("abundance_uncertainty_kind", group.get("abundance_uncertainty_kind", pd.Series(index=group.index, dtype="string")))):
            counts = series.fillna("missing").value_counts()
            add("label_confidence", protein, "descriptive", kind, group, np.nan, np.nan, "NOT_APPLICABLE", f"{kind} has {counts.to_dict()}; no within-protein confidence-regime comparison is available", "results/metadata/task2_counts.csv")
        for model, column in (("ESM1v_single", "ESM1v_single_impairment"), ("ESM2_650M", "ESM2_650M_impairment")):
            count = len(group)
            add("model_coverage", protein, "direct", model, group, direct[(protein, model)]["ap"], 0.0, "PASS", f"common IDs={count}; available-case IDs={count}; coverage=100.000%; AP delta=0.000000", "results/metadata/score_coverage.csv", common_ids=count, available_ids=count)
    for protein, group in primary.groupby("protein", sort=True):
        for model in ("B3", "B4"):
            imputed_group = within.loc[within["protein"].eq(protein) & within["feature_set"].eq(model)]
            imputed = _metrics(imputed_group, "within").iloc[0]
            if complete is None:
                add("structure_missingness", protein, "within", model, group, np.nan, np.nan, "NOT_APPLICABLE", "complete-case model could not be formed", "results/metadata/task5_complete_case_status.csv")
            else:
                complete_group = complete.loc[complete["protein"].eq(protein) & complete["feature_set"].eq(model)]
                complete_metrics = _metrics(complete_group, "within")
                if complete_metrics.empty or not bool(complete_metrics.iloc[0]["valid"]):
                    add("structure_missingness", protein, "within", model, complete_group, np.nan, np.nan, "FAILED", f"complete-case fold/class constraints invalid; n={len(complete_group)}", "results/metadata/task5_complete_case_status.csv")
                else:
                    complete_metric = complete_metrics.iloc[0]
                    add("structure_missingness", protein, "within", model, complete_group, float(complete_metric["ap"]), float(complete_metric["ap"] - imputed["ap"]), "PASS", f"complete-case retraining on same frozen folds; n_complete={len(complete_group)}, n_imputed={len(imputed_group)}, AP delta={complete_metric['ap'] - imputed['ap']:+.6f}", str(external_artifact_path("task5_complete_case_oof_predictions.csv")), common_ids=len(complete_group), available_ids=len(imputed_group))
    inventory = pd.read_csv("results/metadata/assay_inventory.csv")
    for protein in PASS_PROTEINS:
        systems = inventory.loc[inventory["protein_id"].eq({"CYP2C9": "CP2C9_HUMAN", "PTEN": "PTEN_HUMAN"}[protein]), ["role", "host_system", "assay_id"]]
        add("study_system", protein, "descriptive", "assay_system", primary.loc[primary["protein"].eq(protein)], np.nan, np.nan, "NOT_APPLICABLE", f"systems enumerated ({systems.to_dict('records')}); system and assay role are confounded", "results/metadata/assay_inventory.csv")
    overall = {protein: direct[(protein, "ESM1v_single")]["prevalence"] for protein in PASS_PROTEINS}
    for protein, features in pd.read_csv(external_artifact_path("task5_structure_mapping.csv")).groupby("protein"):
        source = primary.loc[primary["protein"].eq(protein)].drop(columns=["site_distance"], errors="ignore").merge(features[["position", "site_distance"]], on="position", how="left")
        for threshold in (4, 5, 8):
            subset = source.loc[source["site_distance"].le(threshold)]
            y = subset["primary_endpoint"].eq("function-impaired")
            status = "PASS" if len(subset) and y.any() and (~y).any() else "FAILED"
            near_rate = float(y.mean()) if len(subset) else np.nan
            enrichment = float(near_rate - overall[protein]) if len(subset) else np.nan
            reason = (f"insufficient class count among near variants (n={len(subset)}, positives={int(y.sum())}, negatives={int((~y).sum())})" if status == "FAILED" else f"descriptive near phenotype rate={near_rate:.6f} versus all-cohort rate={overall[protein]:.6f}; difference={enrichment:+.6f}; denominator n={len(subset)}")
            add(f"proximity_{threshold}A", protein, "descriptive", "site_distance", subset, near_rate, enrichment, status, reason, str(external_artifact_path("task5_structure_mapping.csv")))
    for row in pd.read_csv("results/metadata/task4_observed_permutation_summary.csv").itertuples(index=False):
        hash_valid = verify_external_sha256(str(row.full_draw_output), str(row.full_draw_sha256))
        status = "PASS" if hash_valid else "FAILED"
        metric = float(row.null_mean_ap) if hash_valid else np.nan
        effect = float(row.observed_ap - row.null_mean_ap) if hash_valid else np.nan
        reason = f"Task 4 equal-size position-block null: observed AP={row.observed_ap:.6f}, null mean={row.null_mean_ap:.6f}, effect={row.observed_ap - row.null_mean_ap:+.6f}; external draw hash verified" if hash_valid else "Task 4 permutation draw hash mismatch or missing; null metric not used"
        add("permuted_labels", row.protein, "direct", row.model, primary.loc[primary["protein"].eq(row.protein)], metric, effect, status, reason, "results/metadata/task4_observed_permutation_summary.csv", source_sha256=str(row.full_draw_sha256), hash_validated=hash_valid)
    for row in draw_summary.loc[draw_summary["model"].isin(("B4-B2",))].itertuples(index=False):
        add("opposite_or_no_improvement", row.protein, row.setting, row.model, primary.loc[primary["protein"].eq(row.protein)], row.ap, row.ap, "PASS", "paired B4-B2 AP effect retained, including negative or zero effects", "results/metadata/task5_paired_bootstrap_summary.csv", ci_low=row.ap_ci_low, ci_high=row.ap_ci_high)
    for protein in PASS_PROTEINS:
        add("threshold_alternatives", protein, "all", "frozen", primary.loc[primary["protein"].eq(protein)], np.nan, np.nan, "NOT_APPLICABLE", "NOT_RUN_POST_HOC: no alternative threshold was frozen before Task 4", "config/analysis_freeze.yaml")
    result = pd.DataFrame(rows)
    validate_sensitivity_evidence(result)
    result.to_csv(output, index=False)
    return result


def _figure5(within: pd.DataFrame, lopo: pd.DataFrame, output: Path, score_within: pd.DataFrame | None = None, score_lopo: pd.DataFrame | None = None) -> None:
    if "ap_ci_low" in within.columns:
        rows = pd.concat([within, lopo], ignore_index=True) if not lopo.empty else within.copy()
    else:
        parts = [_metrics(within, "within-protein"), _metrics(lopo, "held-out protein")]
        if score_within is not None:
            parts.append(_metrics(score_within, "within-protein"))
        if score_lopo is not None:
            parts.append(_metrics(score_lopo, "held-out protein"))
        rows = pd.concat(parts, ignore_index=True)
    contrast_rows = rows.loc[rows["model"].isin(("B4-B2",))].copy()
    assert_complete_b4_b2_contrasts(rows)
    rows = rows.loc[rows["model"].isin(("B2", "B3", "B4"))].copy()
    rows["_setting_order"] = rows["setting"].map({"within-protein": 0, "held-out protein": 1})
    rows["_protein_order"] = rows["protein"].map({"CYP2C9": 0, "PTEN": 1})
    rows["_model_order"] = rows["model"].map({"B2": 0, "B3": 1, "B4": 2})
    rows = rows.sort_values(["_setting_order", "_protein_order", "_model_order"]).reset_index(drop=True)
    fig, ax = plt.subplots(figsize=(12, 8.5))
    rows["label"] = rows["setting"] + " / " + rows["protein"] + " / " + rows["model"] + " (prev=" + rows["prevalence"].map(lambda value: f"{value:.3f}") + "; n=" + rows["n_variants"].map(lambda value: str(int(value))) + "; pos=" + rows["n_positions"].map(lambda value: str(int(value))) + ")"
    y = np.arange(len(rows))
    colors = rows["setting"].map({"within-protein": "#2c7fb8", "held-out protein": "#d95f02"})
    for row_index, (_, row) in enumerate(rows.iterrows()):
        low = max(0.0, float(row["ap"] - row["ap_ci_low"]))
        high = max(0.0, float(row["ap_ci_high"] - row["ap"]))
        ax.errorbar(float(row["ap"]), row_index, xerr=[[low], [high]], fmt="o", color="black", ecolor=str(colors.iloc[row_index]), capsize=3)
    ax.scatter(rows["prevalence"], y, marker="|", s=120, color="#777", linewidth=1.5, label="Protein prevalence baseline")
    ax.set_yticks(y, rows["label"])
    ax.invert_yaxis()
    ax.set_ylim(len(rows) - 0.2, -0.8)
    ax.set_xlabel("Average precision (95% position-bootstrap CI; measured positions only)")
    ax.set_title("Figure 5. Generalization of score-only and structure-added models")
    ax.legend(handles=[plt.Line2D([0], [0], marker="o", color="#2c7fb8", linestyle="", label="Within-protein grouped OOF"), plt.Line2D([0], [0], marker="o", color="#d95f02", linestyle="", label="Held-out protein LOPO"), plt.Line2D([0], [0], marker="|", markersize=10, color="#777", linestyle="", label="Protein prevalence baseline")], loc="upper left", bbox_to_anchor=(1.01, 1.0))
    contrasts = contrast_rows
    if not contrasts.empty:
        contrasts = contrasts.sort_values(["setting", "protein"], key=lambda values: values.map({"within-protein": 0, "held-out protein": 1, "CYP2C9": 0, "PTEN": 1}))
        text_lines = ["Paired B4−B2 AP contrasts (95% position-bootstrap CI):"]
        text_lines.extend(f"{r.setting} / {r.protein}: {r.ap:+.3f} [{r.ap_ci_low:+.3f}, {r.ap_ci_high:+.3f}]" for r in contrasts.itertuples())
        fig.text(0.03, 0.035, "\n".join(text_lines), fontsize=8, ha="left", va="bottom")
    fig.subplots_adjust(left=0.38, right=0.78, bottom=0.22, top=0.91)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=180)
    plt.close(fig)


def _figure6(features: pd.DataFrame, primary: pd.DataFrame, output: Path) -> pd.DataFrame:
    # Cases are deterministically selected post-analysis using a recorded rule.
    joined = primary.copy()
    missing_features = [column for column in ("accessibility", "site_distance", "mapping_status") if column not in joined]
    if missing_features:
        joined = joined.merge(features[["protein", "position", *missing_features]], on=["protein", "position"], how="left", validate="many_to_one")
    impaired = joined.loc[joined["primary_endpoint"].eq("function-impaired") & joined["prediction"].notna()]
    false_negative = impaired.loc[impaired["prediction"].lt(0.5)].sort_values(["prediction", "protein", "position", "variant"]).head(1)
    true_positive = impaired.loc[impaired["prediction"].ge(0.5)].sort_values(["prediction", "protein", "position", "variant"], ascending=[False, True, True, True]).head(1)
    uncertain_pool = joined.loc[joined["function_label"].eq("uncertain")]
    medians = joined.groupby("protein")["ESM1v_single_impairment"].median()
    uncertain = uncertain_pool.assign(_distance=(uncertain_pool["ESM1v_single_impairment"] - uncertain_pool["protein"].map(medians)).abs()).sort_values(["_distance", "protein", "position", "variant"]).head(1)
    cases = pd.concat([false_negative.assign(case="false negative"), true_positive.assign(case="true positive"), uncertain.assign(case="uncertain")], ignore_index=True)
    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=False, gridspec_kw={"height_ratios": [3, 1, 0.8]})
    for protein, group in features.groupby("protein", sort=True):
        axes[0].scatter(group["position"], group["site_distance"], s=12, alpha=0.55, label=protein)
    for row in cases.itertuples(index=False):
        if pd.notna(row.site_distance):
            axes[0].scatter(row.position, row.site_distance, s=55, edgecolor="black", linewidth=0.8)
            axes[0].annotate(f"{row.case}: {row.protein} {row.variant}", (row.position, row.site_distance), xytext=(4, 4), textcoords="offset points", fontsize=8)
    axes[0].set_ylabel("Minimum heavy-atom distance to annotated site (Å)")
    axes[0].set_title("Figure 6. Structure/error map; proximity is descriptive, not allostery")
    axes[0].legend()
    for protein, group in features.groupby("protein", sort=True):
        axes[1].plot(group["position"], group["accessibility"], ".", label=protein)
    axes[1].set_xlabel("Reference residue position")
    axes[1].set_ylabel("Relative solvent accessibility")
    axes[2].axis("off")
    lines = []
    for row in cases.itertuples(index=False):
        probability = getattr(row, "prediction", np.nan)
        probability_text = f"OOF p={probability:.3f}" if pd.notna(probability) else "OOF p=not available"
        mapping = getattr(row, "mapping_status", "missing")
        if mapping != "mapped" or pd.isna(getattr(row, "site_distance", np.nan)):
            mapping = "unmapped / no structural distance available"
        lines.append(f"{row.case}: {row.protein} {row.variant} | {probability_text} | phenotype={getattr(row, 'function_label', 'not available')} | {mapping}")
    axes[2].text(0.01, 0.95, "Deterministically selected post-analysis using a recorded rule (not mechanisms or clinical claims):\n" + "\n".join(lines), va="top", fontsize=8)
    fig.subplots_adjust(left=0.10, right=0.96, bottom=0.08, top=0.88, hspace=0.35)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=180)
    plt.close(fig)
    return cases


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--structure-dir", type=Path, default=Path("D:/protein_assay_work/structures"))
    parser.add_argument("--metadata-dir", type=Path, default=Path("results/metadata"))
    parser.add_argument("--figure-dir", type=Path, default=Path("results/figures"))
    parser.add_argument("--config", type=Path, default=Path("config/analysis_freeze.yaml"))
    args = parser.parse_args()
    args.metadata_dir.mkdir(parents=True, exist_ok=True)
    features, provenance = _structure_maps(args.structure_dir)
    for threshold in (4, 5, 8):
        features[f"proximity_{threshold}A"] = assign_proximity(features, threshold)
    structure_path = external_artifact_path("task5_structure_mapping.csv")
    structure_path.parent.mkdir(parents=True, exist_ok=True)
    features.to_csv(structure_path, index=False)
    primary = _joined_primary()
    for column in ("structure_id", "mapping_status", "accessibility", "contacts", "site_distance", "secondary_structure"):
        primary = primary.merge(features[["protein", "position", column]], on=["protein", "position"], how="left", validate="many_to_one")
    within = compare_structure_models(primary, fold_column="fold", feature_sets=("B3", "B4"))
    assert_common_variant_ids(within.loc[within["feature_set"].eq("B3")], within.loc[within["feature_set"].eq("B4")])
    structure_oof_path = external_artifact_path("task5_oof_predictions.csv")
    structure_oof_path.parent.mkdir(parents=True, exist_ok=True)
    within.to_csv(structure_oof_path, index=False)
    complete_base = structure_complete_case(primary)
    complete_within: pd.DataFrame | None = None
    try:
        complete_within = compare_structure_models(complete_base, fold_column="fold", feature_sets=("B3", "B4"))
        complete_within.to_csv(external_artifact_path("task5_complete_case_oof_predictions.csv"), index=False)
    except ValueError as error:
        pd.DataFrame([{"status": "FAILED", "reason": str(error), "n_variants": len(complete_base), "n_positions": complete_base["position"].nunique()}]).to_csv(args.metadata_dir / "task5_complete_case_status.csv", index=False)
    # Task 4's exact LOPO folds are retained; train/test separation remains by protein.
    lopo = []
    for held_out in PASS_PROTEINS:
        test = primary.loc[primary["protein"].eq(held_out)].copy()
        train = primary.loc[~primary["protein"].eq(held_out)].copy()
        # Reuse each held-out row's Task 4 LOPO fold marker and fit a frozen-C
        # structure model on the other protein with training-only preprocessing.
        merged = pd.concat([train.assign(_heldout=False), test.assign(_heldout=True)], ignore_index=True)
        # compare_structure_models is the common implementation; a fold value
        # per protein gives one held-out fold and prevents position leakage.
        merged["lopo_fold"] = merged["_heldout"].astype(int)
        part = compare_structure_models(merged, fold_column="lopo_fold", feature_sets=("B3", "B4"))
        lopo.append(part.loc[part["protein"].eq(held_out)].assign(held_out_protein=held_out))
    lopo_frame = pd.concat(lopo, ignore_index=True)
    structure_lopo_path = external_artifact_path("task5_lopo_predictions.csv")
    lopo_frame.to_csv(structure_lopo_path, index=False)
    task4_within = pd.read_csv(external_artifact_path("task4_oof_predictions.csv"))
    task4_within = task4_within.loc[task4_within["feature_set"].eq("B2")]
    task4_lopo = pd.read_csv(external_artifact_path("task4_lopo_predictions.csv"))
    task4_lopo = task4_lopo.loc[task4_lopo["feature_set"].eq("B2")]
    within_all = pd.concat([task4_within, within], ignore_index=True)
    lopo_all = pd.concat([task4_lopo, lopo_frame], ignore_index=True)
    draw_path = Path("D:/protein_assay_work/processed/task5_paired_bootstrap_draws.csv")
    draw_path.unlink(missing_ok=True)
    within_boot = _bootstrap_summaries(within_all, "within-protein", draw_path)
    lopo_boot = _bootstrap_summaries(lopo_all, "held-out protein", draw_path)
    draw_summary = pd.concat([within_boot, lopo_boot], ignore_index=True)
    draw_summary.to_csv(args.metadata_dir / "task5_paired_bootstrap_summary.csv", index=False)
    metrics = pd.concat([_metrics(task4_within, "within-protein"), _metrics(task4_lopo, "held-out protein"), _metrics(within, "within-protein"), _metrics(lopo_frame, "held-out protein")], ignore_index=True)
    metrics.to_csv(args.metadata_dir / "task5_metrics.csv", index=False)
    function_source = Path("D:/protein_assay_work/processed/function_sensitivity_scores.csv")
    function_hash = "3be0cc1eec7ef6b3da5da9289c22e1170758eaeaa773692741b554b83888be4b"
    source_valid = verify_external_sha256(str(function_source), function_hash)
    alternate_path = args.metadata_dir / "task5_function_score_sensitivity.csv"
    alternate = None
    if source_valid:
        alternate = _alternate_score_metrics(primary, function_source)
        alternate.to_csv(alternate_path, index=False)
    sensitivity = _sensitivity_results(primary, within, complete_within, lopo_frame, alternate, draw_summary, draw_path, args.metadata_dir / "task5_sensitivity_results.csv")
    sensitivity.to_csv(args.metadata_dir / "task5_sensitivity.csv", index=False)
    # The case figure uses the B2 probability from Task 4 OOF predictions.
    b2 = pd.read_csv(external_artifact_path("task4_oof_predictions.csv"))
    b2 = b2.loc[b2["feature_set"].eq("B2"), ["protein", "variant", "position", "prediction"]]
    primary_cases = primary.merge(b2, on=["protein", "variant", "position"], how="left", validate="one_to_one")
    atlas = pd.read_csv(external_artifact_path("assay_atlas.csv"))
    uncertain = atlas.loc[atlas["protein"].isin(PASS_PROTEINS) & atlas["abundance_label"].eq("preserved") & atlas["function_label"].eq("uncertain")].copy()
    uncertain = uncertain.merge(features[["protein", "position", "accessibility", "site_distance", "mapping_status"]], on=["protein", "position"], how="left", validate="many_to_one")
    primary_cases = pd.concat([primary_cases, uncertain], ignore_index=True, sort=False)
    cases = _figure6(features, primary_cases, args.figure_dir / "figure6_structure_error_map.png")
    cases.to_csv(args.metadata_dir / "task5_case_studies.csv", index=False)
    _figure5(draw_summary, pd.DataFrame(columns=draw_summary.columns), args.figure_dir / "figure5_generalization.png")
    source_rows = sum(1 for _ in function_source.open("rb")) - 1 if function_source.exists() else 0
    alternate_info = {"path": str(alternate_path), "sha256": _sha256(alternate_path), "rows": int(pd.read_csv(alternate_path).shape[0])} if alternate_path.exists() else {"path": str(alternate_path), "status": "NOT_RUN_HASH_INVALID"}
    outputs = [external_artifact_path(n) for n in ("task5_structure_mapping.csv", "task5_oof_predictions.csv", "task5_lopo_predictions.csv", "task5_complete_case_oof_predictions.csv") if external_artifact_path(n).exists()] + [args.metadata_dir / n for n in ("task5_paired_bootstrap_summary.csv", "task5_sensitivity_results.csv", "task5_case_studies.csv") if (args.metadata_dir / n).exists()]
    figures = [args.figure_dir / n for n in ("figure5_generalization.png", "figure6_structure_error_map.png") if (args.figure_dir / n).exists()]
    provenance_out = {"code_version": "task5-fix1", "inputs": {"cohort": {"path": "D:/protein_assay_work/processed/paired_phenotype_cohort.csv", "sha256": _sha256(Path("D:/protein_assay_work/processed/paired_phenotype_cohort.csv"))}, "atlas": {"path": str(external_artifact_path("assay_atlas.csv")), "sha256": _sha256(external_artifact_path("assay_atlas.csv"))}, "task4_oof": {"path": str(external_artifact_path("task4_oof_predictions.csv")), "sha256": _sha256(external_artifact_path("task4_oof_predictions.csv"))}, "task4_lopo": {"path": str(external_artifact_path("task4_lopo_predictions.csv")), "sha256": _sha256(external_artifact_path("task4_lopo_predictions.csv"))}, "task4_permutation_summary": {"path": "results/metadata/task4_observed_permutation_summary.csv", "sha256": _sha256(Path("results/metadata/task4_observed_permutation_summary.csv"))}, "label_counts": {"path": "results/metadata/task2_counts.csv", "sha256": _sha256(Path("results/metadata/task2_counts.csv"))}}, "structures": provenance, "outputs": {str(path): {"sha256": _sha256(path), "rows": int(pd.read_csv(path).shape[0]) if path.suffix == ".csv" else None} for path in [*outputs, *figures]}, "function_sensitivity_source": {"path": str(function_source), "sha256": function_hash, "hash_validated": source_valid, "rows": source_rows}, "function_sensitivity_metrics": alternate_info, "paired_bootstrap": {"path": "D:/protein_assay_work/processed/task5_paired_bootstrap_draws.csv", "sha256": _sha256(draw_path), "rows": sum(1 for _ in draw_path.open("rb")) - 1, "seed": 2026, "draws_per_protein_setting": 2000, "cohort_rule": "exact common canonical protein/variant/position IDs; one shared residue-position draw per protein and setting"}, "sensitivity_evidence": {"canonical_path": str(args.metadata_dir / "task5_sensitivity_results.csv"), "sha256": _sha256(args.metadata_dir / "task5_sensitivity_results.csv"), "required_controls": sorted(pd.read_csv(args.metadata_dir / "task5_sensitivity_results.csv")["control"].unique().tolist()), "legacy_alias": {"path": str(args.metadata_dir / "task5_sensitivity.csv"), "sha256": _sha256(args.metadata_dir / "task5_sensitivity.csv"), "role": "backward-compatible byte-for-byte alias; canonical evidence is task5_sensitivity_results.csv"}}, "primary_proteins": PASS_PROTEINS, "proximity_rule": "minimum heavy-atom distance <=5 Å descriptive; 4/8 Å sensitivity", "case_rule": "deterministically selected post-analysis using a recorded rule; Task 4 B2 OOF false-negative lowest probability; true-positive highest probability; uncertain abundance-preserved/function-uncertain closest to within-protein median ESM1v score; NOT_AVAILABLE is retained when no primary OOF row exists"}
    (args.metadata_dir / "task5_provenance.json").write_text(json.dumps(provenance_out, indent=2) + "\n", encoding="utf-8")
    update_analysis_freeze(args.config)
    print(metrics.to_json(orient="records", indent=2))


if __name__ == "__main__":
    main()
